### ISSUE TITLE
ScriptUnit cannot handle dividing non-terminating floating number

### ISSUE THREAD

**Issue by risa-kit** [dakusui/scriptunit#2]
Caused by: java.lang.ArithmeticException: Non-terminating decimal expansion; no exact representable decimal result.
at java.math.BigDecimal.divide(BigDecimal.java:1690)
at com.github.dakusui.scriptunit.drivers.Arith.calc(Arith.java:52)
at com.github.dakusui.scriptunit.drivers.Arith.lambda$div$7(Arith.java:40)
... 127 more

**Comment by dakusui** [comment]
The fix was merged and will be ok in the next release.
